// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRvo_1lWMdDPna-A3qyIYSs6RNyOeKEY8',
    appId: '1:935607995991:android:d66acab06e2af9e07a9d12',
    messagingSenderId: '935607995991',
    projectId: 'pasabahce-d1741',
    storageBucket: 'pasabahce-d1741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWI7LWUZrbl96H3GXRmQeF417T-EDUi88',
    appId: '1:935607995991:ios:6d10dd6675d214ab7a9d12',
    messagingSenderId: '935607995991',
    projectId: 'pasabahce-d1741',
    storageBucket: 'pasabahce-d1741.appspot.com',
    androidClientId: '935607995991-u5p075vl5n0m1ugsjrk5lp0qkek9ev2a.apps.googleusercontent.com',
    iosClientId: '935607995991-dgbd3q71rlcht2r4sd9aneaota7ha0bg.apps.googleusercontent.com',
    iosBundleId: 'com.pasabahcee.pasabahcee',
  );
}
